const Quesions = [
  {
    type: "multiple",
    difficulty: "medium",
    category: "Entertainment: Music",
    question: "What&#039;s the most common time signature for rock songs?",
    correct_answer: "4/4",
    incorrect_answers: ["1/2", "8/12", "2/4"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Mythology",
    question:
      "Which of the following Mesopotamian mythological figures was NOT a deity?",
    correct_answer: "Enkidu",
    incorrect_answers: ["Enki", "Enlil", "Enkimdu"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Geography",
    question: "Which city is the capital of Switzerland?",
    correct_answer: "Bern",
    incorrect_answers: ["Z&uuml;rich", "Frankfurt", "Wien"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "What was the first commerically available computer processor?",
    correct_answer: "Intel 4004",
    incorrect_answers: ["Intel 486SX", "TMS 1000", "AMD AM386"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Vehicles",
    question: "How much horsepower is produced by the SD40-2 Locomotive?",
    correct_answer: "3,000",
    incorrect_answers: ["3,200", "2,578", "2,190"],
  },
  {
    type: "boolean",
    difficulty: "medium",
    category: "Vehicles",
    question: "The majority of Subaru vehicles are made in China.",
    correct_answer: "False",
    incorrect_answers: ["True"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Vehicles",
    question:
      "Which Italian city is home of the car manufacturer &#039;Fiat&#039;?",
    correct_answer: "Turin",
    incorrect_answers: ["Maranello", "Modena", "Rome"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Animals",
    question: "What is the scientific name for modern day humans?",
    correct_answer: "Homo Sapiens",
    incorrect_answers: [
      "Homo Ergaster",
      "Homo Erectus",
      "Homo Neanderthalensis",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "Which of these is a stop codon in DNA?",
    correct_answer: "TAA",
    incorrect_answers: ["ACT", "ACA", "GTA"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Entertainment: Video Games",
    question: "The &#039;64&#039; in the Nintendo-64 console refers to what?",
    correct_answer: "The bits in the CPU architecture",
    incorrect_answers: [
      "The number of megabytes of RAM",
      "Capacity of the ROM Cartridges in megabytes",
      "Clock speed of the CPU in Hertz",
    ],
  },
];
