export const Engineering_Questions = [
  {
    text: "Solve this:",
    image: [
      {
        imgUrl:
          "https://res.cloudinary.com/dikrruxtt/image/upload/v1714915428/q_mf93ze.png",
        img_Id: "id01",
      },
    ],
    isSaved: false,
    isReviewed: false,
    // _id: "a",
    selectedOption: "",
    subject: "math",
    options: ["b", "a", "c", "d"],
  },
  {
    text: "Find the value of 'x' in the equation 3x + 5 = 17:",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "1",
    selectedOption: "",
    subject: "math",
    options: ["4", "6", "12", "none"],
  },
  {
    text: "What is the area of a triangle with base 6 units and height 8 units?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "2",
    selectedOption: "",
    subject: "math",
    options: ["24", "36", "48", "none"],
  },

  {
    text: "What is the value of 'x' in the equation 4x^2 - 16 = 0?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "3",
    selectedOption: "",
    subject: "math",
    options: ["±2", "±4", "±8", "none"],
  },
  {
    text: "If f(x) = 3x^2 + 2x - 5, what is f'(x) (the derivative of f(x))?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "4",
    selectedOption: "",
    subject: "math",
    options: ["6x + 2", "3x^2 + 2x", "6x + 2x", "none"],
  },
  {
    text: "What is the solution to the system of equations: x + y = 7, 2x - y = 1?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "5",
    selectedOption: "",
    subject: "math",
    options: ["x = 2, y = 5", "x = 3, y = 4", "x = 4, y = 3", "none"],
  },
  {
    text: "Find the value of 'x' in the equation log₃(x + 1) = 2:",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "6",
    selectedOption: "",
    subject: "math",
    options: ["8", "26", "1/3", "none"],
  },

  {
    text: "If a triangle has sides of lengths 3, 4, and 5 units, what type of triangle is it?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "7",
    selectedOption: "",
    subject: "math",
    options: ["Right angled", "Equilateral", "Isosceles", "none"],
  },

  {
    text: "What is the SI unit of force?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "8",
    selectedOption: "",
    subject: "physics",
    options: ["Newton", "Joule", "Watt", "none"],
  },

  {
    text: "What is the SI unit of power?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "9",
    selectedOption: "",
    subject: "physics",
    options: ["Watt", "Joule", "Newton", "none"],
  },
  {
    text: "What is the formula for Ohm's Law?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "10",
    selectedOption: "",
    subject: "physics",
    options: ["V = I * R", "V = I + R", "V = I / R", "none"],
  },
  {
    text: "What is the principle behind the functioning of a transformer?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "11",
    selectedOption: "",
    subject: "physics",
    options: [
      "Electromagnetic induction",
      "Electrostatic induction",
      "Nuclear fusion",
      "none",
    ],
  },
  {
    text: "What is the SI unit of electric current?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "12",
    selectedOption: "",
    subject: "physics",
    options: ["Ampere", "Coulomb", "Volt", "none"],
  },
  {
    text: "What does the term 'terminal velocity' refer to?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "13",
    selectedOption: "",
    subject: "physics",
    options: [
      "The constant speed that a freely falling object eventually reaches when the resistance of the medium through which it is falling prevents further acceleration",
      "The maximum velocity a body can achieve",
      "The velocity at which a body starts falling",
      "none",
    ],
  },
  {
    text: "What is the chemical symbol for Gold?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "14",
    selectedOption: "",
    subject: "chemistry",
    options: ["Au", "Ag", "Hg", "none"],
  },
  {
    text: "What is the formula for water?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "15",
    selectedOption: "",
    subject: "chemistry",
    options: ["H₂O", "CO₂", "NaCl", "none"],
  },
  {
    text: "What is the pH value of a neutral solution?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "16",
    selectedOption: "",
    subject: "chemistry",
    options: ["7", "8", "6", "none"],
  },
  {
    text: "What is the process of conversion of a solid directly into vapor called?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "17",
    selectedOption: "",
    subject: "chemistry",
    options: ["Sublimation", "Evaporation", "Condensation", "none"],
  },
  {
    text: "Which gas is responsible for the greenhouse effect?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "18",
    selectedOption: "",
    subject: "chemistry",
    options: ["Carbon dioxide", "Oxygen", "Nitrogen", "none"],
  },

  {
    text: "What is the lightest element in the periodic table?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "19",
    selectedOption: "",
    subject: "chemistry",
    options: ["Hydrogen", "Helium", "Lithium", "none"],
  },
  {
    text: "What is the chemical formula of ammonia?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "20",
    selectedOption: "",
    subject: "chemistry",
    options: ["NH₃", "NH₄Cl", "N₂O", "none"],
  },

  {
    text: "Which of the following words is a synonym for 'happy'?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "21",
    selectedOption: "",
    subject: "english",
    options: ["Joyful", "Sad", "Angry", "none"],
  },

  {
    text: "Choose the correct spelling: a) Occassion b) Occasion c) Ocaasion",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "22",
    selectedOption: "",
    subject: "english",
    options: ["b", "a", "c", "none"],
  },
  {
    text: "What is a group of crows called?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "23",
    selectedOption: "",
    subject: "english",
    options: ["Murder", "Pack", "Flock", "none"],
  },
  {
    text: "Which of the following sentences is grammatically correct? a) She were walking down the street. b) She was walking down the street. c) She did walked down the street.",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "24",
    selectedOption: "",
    subject: "english",
    options: ["b", "a", "c", "none"],
  },

  {
    text: "What is the comparative form of 'good'?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "25",
    selectedOption: "",
    subject: "english",
    options: ["Better", "Best", "Gooder", "none"],
  },
  {
    text: "Which word is a noun: a) Quickly b) Happy c) Book",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "26",
    selectedOption: "",
    subject: "english",
    options: ["c", "a", "b", "none"],
  },
  {
    text: "Which of the following is a preposition: a) Under b) Jumping c) Angry",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "27",
    selectedOption: "",
    subject: "english",
    options: ["a", "b", "c", "none"],
  },
  {
    text: "If all Bloops are Razzies and all Razzies are Lazzies, then are all Bloops definitely Lazzies?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "28",
    selectedOption: "",
    subject: "iq",
    options: ["Yes", "No", "Maybe", "none"],
  },
  {
    text: "If a plane crashes on the border of the United States and Mexico, where do they bury the survivors?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "29",
    selectedOption: "",
    subject: "iq",
    options: [
      "You don't bury survivors",
      "On the border",
      "In their hometowns",
      "none",
    ],
  },

  {
    text: "Which number should come next in the series: 1, 4, 9, 16, ___?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "30",
    selectedOption: "",
    subject: "iq",
    options: ["25", "36", "49", "none"],
  },
  {
    text: "If you rearrange the letters 'CIFAIPC', you would have the name of a(n):",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "31",
    selectedOption: "",
    subject: "iq",
    options: ["Ocean", "Country", "Animal", "none"],
  },
  {
    text: "Which of the following is not a prime number: 11, 21, 31, 41?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "32",
    selectedOption: "",
    subject: "iq",
    options: ["21", "41", "31", "none"],
  },

  {
    text: "What is the next number in the sequence: 2, 6, 12, 20, ___?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "33",
    selectedOption: "",
    subject: "iq",
    options: ["30", "36", "40", "none"],
  },
  {
    text: "Mary's father has five daughters: 1. Nana, 2. Nene, 3. Nini, 4. Nono. What is the name of the fifth daughter?",
    image: [],
    isSaved: false,
    isReviewed: false,
    // _id: "34",
    selectedOption: "",
    subject: "iq",
    options: ["Mary", "Nunu", "None", "none"],
  },
];

export const Business_Questions = [
  {
    // _id: 2,
    text: "If a business has $500 in expenses and earns $800 in revenue, what is its profit?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["$300", "$200", "$100", "none"],
  },
  {
    // _id: 3,
    text: "Calculate the percentage increase if a company's sales rose from $5000 to $6000.",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["20%", "10%", "25%", "none"],
  },
  {
    // _id: 4,
    text: "A company's profit margin is 25%. If its revenue is $10,000, what is its profit?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["$2500", "$2000", "$1500", "none"],
  },
  {
    // _id: 5,
    text: "If a business buys 100 units of a product for $5 each and sells them for $10 each, what is its profit?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["$500", "$1000", "$250", "none"],
  },
  {
    // _id: 6,
    text: "A company's fixed costs are $1000, and its variable costs per unit are $5. How many units must it sell to break even if it sells each unit for $10?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["200", "100", "150", "none"],
  },

  {
    // _id: 8,
    text: "If a business earns $5000 in revenue and has a profit margin of 20%, what is its profit?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["$1000", "$2000", "$1500", "none"],
  },
  {
    // _id: 9,
    text: "A company's assets are worth $10,000, and its liabilities are $5000. What is its equity?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "math",
    options: ["$5000", "$10,000", "$15,000", "none"],
  },

  {
    // _id: 11,
    text: "What does the acronym 'SWOT' stand for in business analysis?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "english",
    options: [
      "Strengths, Weaknesses, Opportunities, Threats",
      "Sales, Work, Operations, Team",
      "Strategy, Workforce, Organization, Technology",
      "none",
    ],
  },
  {
    // _id: 12,
    text: "Define 'ROI' in business terms.",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "english",
    options: [
      "Return on Investment",
      "Revenue on Interest",
      "Rate of Inflation",
      "none",
    ],
  },
  {
    // _id: 13,
    text: "What is the 'Pareto Principle' also known as?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "english",
    options: [
      "The 80/20 rule",
      "The Golden Ratio",
      "The Rule of Thirds",
      "none",
    ],
  },
  {
    // _id: 14,
    text: "What does 'KPI' stand for in business?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "english",
    options: [
      "Key Performance Indicator",
      "Knowledge and Practice Integration",
      "Keep Progressing Indefinitely",
      "none",
    ],
  },
  {
    // _id: 20,
    text: "Explain the term 'Cash Flow' in business finance.",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "english",
    options: [
      "The net amount of cash and cash-equivalents being transferred into and out of a business",
      "The total revenue generated by a business",
      "The profit made by a business",
      "none",
    ],
  },
  {
    // _id: 21,
    text: "If a car travels 60 miles in 1 hour, how many miles will it travel in 3 hours at the same speed?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "iq",
    options: ["180 miles", "120 miles", "240 miles", "none"],
  },
  // Remaining questions...
  {
    // _id: 22,
    text: "If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "iq",
    options: ["5 minutes", "1 minute", "10 minutes", "none"],
  },
  {
    // _id: 23,
    text: "What comes next in the series: 3, 6, 9, 12, ___?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "iq",
    options: ["15", "18", "21", "none"],
  },
  {
    // _id: 24,
    text: "A snail climbs up a 10-foot wall. Each day it climbs 3 feet, but at night it slips back 2 feet. How many days does it take for the snail to reach the top of the wall?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "iq",
    options: ["8 days", "10 days", "12 days", "none"],
  },
  {
    // _id: 25,
    text: "What is the missing number in the sequence: 1, 4, 9, 16, ___?",
    image: [],
    isSaved: false,
    isReviewed: false,
    selectedOption: "",
    subject: "iq",
    options: ["25", "36", "49", "none"],
  },
];
